//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 

namespace DEXPI {

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = true)]
    public partial class PlantModel : PlantItemCollection {

        /// <remarks/>
        public PlantInformation PlantInformation;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PlantStructureItem")]
        public PlantStructureItem[] PlantStructureItem;

        /// <remarks/>
        public Extent Extent;

        /// <remarks/>
        public Drawing Drawing;

        /// <remarks/>
        public ShapeCatalogue ShapeCatalogue;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PipingNetworkSystem")]
        public PipingNetworkSystem[] PipingNetworkSystem;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Equipment")]
        public Equipment[] Equipment;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InstrumentComponent")]
        public InstrumentComponent[] InstrumentComponent;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InstrumentLoop")]
        public InstrumentLoop[] InstrumentLoop;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InstrumentationLoopFunction")]
        public InstrumentationLoopFunction[] InstrumentationLoopFunction;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ProcessInstrumentationFunction")]
        public ProcessInstrumentationFunction[] ProcessInstrumentationFunction;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ProcessSignalGeneratingSystem")]
        public ProcessSignalGeneratingSystem[] ProcessSignalGeneratingSystem;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ActuatingSystem")]
        public ActuatingSystem[] ActuatingSystem;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PlantInformation : A_LoopObj {

        /// <remarks/>
        public UnitsOfMeasure UnitsOfMeasure;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Application;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ApplicationVersion;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SchemaVersion;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OriginatingSystem;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ProjectName;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CompanyName;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Date;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Time;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Is3D;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Units;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Discipline;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UnitsOfMeasure : A_LoopObj {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Area;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Angle;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Distance;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Temperature;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Pressure;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Volume;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Weight;
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ShapeCatalogue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DrawingBorder))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CrossPageConnection))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NominalDiameter))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Connection))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ConnectionPoints))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Scale))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PersistentID))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Reference))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Axis))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Position))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Coordinate))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Curve))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PolyLine))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Shape))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Ellipse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Circle))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TrimmedCurve))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Line))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Presentation))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Drawing))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Location))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Extent))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GenericAttribute))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GenericAttributes))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Association))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UnitsOfMeasure))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PlantInformation))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PlantItemCollection))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PlantItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PipingNetworkSystem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InstrumentLoop))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InstrumentConnection))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PipeOffPageConnectorReference))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PipeOffPageConnectorReferenceByNumber))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PipingNetworkSegment))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InformationFlow))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Component))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Text))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InstrumentationLoopFunction))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PropertyBreak))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InsulationSymbol))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PipeFlowArrow))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProcessInstrument))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LinkedPersistentID))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PipeOffPageConnector))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PipingComponent))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PipeTee))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Gap))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CenterLine))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProcessInstrumentationFunction))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProcessSignalGeneratingFunction))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ActuatingFunction))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProcessSignalGeneratingSystem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProcessSignalGeneratingSystemComponent))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ActuatingSystem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ActuatingSystemComponent))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OperatedValveReference))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ControlledActuator))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Label))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InstrumentComponent))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Nozzle))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Equipment))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Chamber))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PumpEquipmentChamber))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PumpEquipment))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Displacer))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Impeller))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SubTaggedColumnSection))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ColumnInternalsArrangement))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TaggedColumnSection))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PipingNode))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PlantModel))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class A_LoopObj {
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ComponentShapeOfNozzle))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ComponentShapeOfPipingComponent))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ComponentShapeOfPipeFlowArrow))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ComponentShapeOfPipeOffPageConnector))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ComponentShapeOfInstrumentComponent))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ComponentShapeOfProcessInstrument))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ComponentShapeOfProcessInstrumentationFunction))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ComponentShapeOfInstrumentationLoopFunction))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ComponentShapeOfProcessSignalGeneratingFunction))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ComponentShapeOfComponent))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ComponentShapeOfPropertyBreak))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ComponentShapeOfControlledActuator))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ComponentShapeOfInsulationSymbol))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ComponentShapeOfEquipment))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public abstract partial class ComponentShape {

        /// <remarks/>
        public ConnectionPoints ConnectionPoints;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Line")]
        public Line[] Line;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PolyLine")]
        public PolyLine[] PolyLine;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Circle")]
        public Circle[] Circle;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Ellipse")]
        public Ellipse[] Ellipse;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TrimmedCurve")]
        public TrimmedCurve[] TrimmedCurve;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Shape")]
        public Shape[] Shape;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Text")]
        public Text[] Text;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GenericAttributes")]
        public GenericAttributes[] GenericAttributes;

        /// <remarks/>
        public Position Position;

        /// <remarks/>
        public Extent Extent;

        /// <remarks/>
        public Position SPPID_Position;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ComponentName;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ID;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConnectionPoints : A_LoopObj {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Node")]
        public PipingNode[] Node;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int NumPoints;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int FlowIn;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FlowInSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int FlowOut;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FlowOutSpecified;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PipingNode : PlantItem {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Type;
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PipingNetworkSystem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InstrumentLoop))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InstrumentConnection))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PipeOffPageConnectorReference))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PipeOffPageConnectorReferenceByNumber))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PipingNetworkSegment))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InformationFlow))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Component))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Text))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InstrumentationLoopFunction))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PropertyBreak))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InsulationSymbol))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PipeFlowArrow))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProcessInstrument))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LinkedPersistentID))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PipeOffPageConnector))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PipingComponent))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PipeTee))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Gap))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CenterLine))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProcessInstrumentationFunction))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProcessSignalGeneratingFunction))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ActuatingFunction))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProcessSignalGeneratingSystem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProcessSignalGeneratingSystemComponent))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ActuatingSystem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ActuatingSystemComponent))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OperatedValveReference))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ControlledActuator))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Label))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InstrumentComponent))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Nozzle))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Equipment))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Chamber))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PumpEquipmentChamber))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PumpEquipment))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Displacer))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Impeller))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SubTaggedColumnSection))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ColumnInternalsArrangement))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TaggedColumnSection))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PipingNode))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PlantItem : PlantItemCollection {

        /// <remarks/>
        public PersistentID PersistentID;

        /// <remarks/>
        public Presentation Presentation;

        /// <remarks/>
        public Extent Extent;

        /// <remarks/>
        public Position Position;

        /// <remarks/>
        public Scale Scale;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GenericAttributes")]
        public GenericAttributes[] GenericAttributes;

        /// <remarks/>
        public ConnectionPoints ConnectionPoints;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Association")]
        public Association[] Association;

        /// <remarks/>
        public Position SPPID_Position;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Label")]
        public Label[] Label;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Text")]
        public Text[] Text;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ID;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ComponentName;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ComponentClass;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ComponentClassURI;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TagName;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PersistentID : A_LoopObj {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Identifier;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Context;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Presentation : A_LoopObj {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Layer;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Color;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double R;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double G;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double B;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LineWeight;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LineType;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Extent : A_LoopObj {

        /// <remarks/>
        public Location Min;

        /// <remarks/>
        public Location Max;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Location : A_LoopObj {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double X;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double Y;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double Z;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Position : A_LoopObj {

        /// <remarks/>
        public Location Location;

        /// <remarks/>
        public Axis Axis;

        /// <remarks/>
        public Reference Reference;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Axis : A_LoopObj {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double X;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double Y;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double Z;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Reference : A_LoopObj {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double X;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double Y;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double Z;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Scale : A_LoopObj {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double X;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double Y;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double Z;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GenericAttributes : A_LoopObj {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GenericAttribute")]
        public GenericAttribute[] GenericAttribute;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Number;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Set;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GenericAttribute : A_LoopObj {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Format;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Units;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string UnitsURI;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AttributeURI;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ValueURI;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Association : A_LoopObj {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public AssociationType Type;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ItemID;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    public enum AssociationType {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("is about")]
        isabout,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("is a subject of")]
        isasubjectof,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("is associated with")]
        isassociatedwith,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("is a boundary of")]
        isaboundaryof,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("refers to")]
        refersto,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("is referenced by")]
        isreferencedby,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("is referenced in")]
        isreferencedin,

        /// <remarks/>
        describes,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("is described in")]
        isdescribedin,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("indirectly describes")]
        indirectlydescribes,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("is indirectly described in")]
        isindirectlydescribedin,

        /// <remarks/>
        defines,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("is defined in")]
        isdefinedin,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("is defined by")]
        isdefinedby,

        /// <remarks/>
        contains,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("is contained in")]
        iscontainedin,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("indirectly defines")]
        indirectlydefines,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("is indirectly defined in")]
        isindirectlydefinedin,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("is connected to")]
        isconnectedto,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("is logically connected to")]
        islogicallyconnectedto,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("has logical start")]
        haslogicalstart,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("is logical start of")]
        islogicalstartof,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("has logical end")]
        haslogicalend,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("is logical end of")]
        islogicalendof,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("is involved with role in")]
        isinvolvedwithrolein,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("is an activity with role involving")]
        isanactivitywithroleinvolving,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("is fulfilled by")]
        isfulfilledby,

        /// <remarks/>
        fulfills,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("is a part of")]
        isapartof,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("is an assembly including")]
        isanassemblyincluding,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("is a component of")]
        isacomponentof,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("is a composition including")]
        isacompositionincluding,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("is an element of")]
        isanelementof,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("is a collection including")]
        isacollectionincluding,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("is identified by")]
        isidentifiedby,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("is an identifier for")]
        isanidentifierfor,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("is a template including")]
        isatemplateincluding,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("is a component of template")]
        isacomponentoftemplate,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("is a template that refers to")]
        isatemplatethatrefersto,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("is a reference in template")]
        isareferenceintemplate,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("is classified as")]
        isclassifiedas,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("is incidentally classified as")]
        isincidentallyclassifiedas,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("has dataset")]
        hasdataset,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("is a dataset of")]
        isadatasetof,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("is a comment referring to")]
        isacommentreferringto,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("is referenced in comment")]
        isreferencedincomment,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("has document")]
        hasdocument,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("is a document for")]
        isadocumentfor,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("is the location of")]
        isthelocationof,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("is located in")]
        islocatedin,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("is upstream of")]
        isupstreamof,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("is downstream of")]
        isdownstreamof,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("is the responsibility of")]
        istheresponsibilityof,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Label : Component {
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Text))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InstrumentationLoopFunction))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PropertyBreak))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InsulationSymbol))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PipeFlowArrow))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProcessInstrument))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LinkedPersistentID))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PipeOffPageConnector))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PipingComponent))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PipeTee))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Gap))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CenterLine))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProcessInstrumentationFunction))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProcessSignalGeneratingFunction))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ActuatingFunction))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProcessSignalGeneratingSystem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProcessSignalGeneratingSystemComponent))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ActuatingSystem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ActuatingSystemComponent))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OperatedValveReference))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ControlledActuator))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Label))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InstrumentComponent))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Nozzle))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Equipment))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Chamber))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PumpEquipmentChamber))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PumpEquipment))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Displacer))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Impeller))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SubTaggedColumnSection))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ColumnInternalsArrangement))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TaggedColumnSection))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Component : PlantItem {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Line")]
        public Line[] Line;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PolyLine")]
        public PolyLine[] PolyLine;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Circle")]
        public Circle[] Circle;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Ellipse")]
        public Ellipse[] Ellipse;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TrimmedCurve")]
        public TrimmedCurve[] TrimmedCurve;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Shape")]
        public Shape[] Shape;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Equipment")]
        public Equipment[] Equipment;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InstrumentComponent")]
        public InstrumentComponent[] InstrumentComponent;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Line : Curve {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Coordinate")]
        public Coordinate[] Coordinate;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Coordinate : A_LoopObj {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double X;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double Y;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double Z;
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PolyLine))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Shape))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Ellipse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Circle))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TrimmedCurve))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Line))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Curve : A_LoopObj {

        /// <remarks/>
        public Presentation Presentation;

        /// <remarks/>
        public Extent Extent;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PolyLine : Curve {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Coordinate")]
        public Coordinate[] Coordinate;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int NumPoints;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Shape : Curve {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Coordinate")]
        public Coordinate[] Coordinate;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int NumPoints;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Ellipse : Curve {

        /// <remarks/>
        public Position Position;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double PrimaryAxis;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double SecondaryAxis;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Circle : Curve {

        /// <remarks/>
        public Position Position;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double Radius;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TrimmedCurve : Curve {

        /// <remarks/>
        public Circle Circle;

        /// <remarks/>
        public Ellipse Ellipse;

        /// <remarks/>
        public Position Position;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double StartAngle;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double EndAngle;
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Chamber))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PumpEquipmentChamber))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PumpEquipment))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Displacer))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Impeller))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SubTaggedColumnSection))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ColumnInternalsArrangement))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TaggedColumnSection))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Equipment : Component {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Nozzle")]
        public Nozzle[] Nozzle;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Nozzle : Component {
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PumpEquipmentChamber))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Chamber : Equipment {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PumpEquipmentChamber : Chamber {
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Displacer))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Impeller))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PumpEquipment : Equipment {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Displacer : PumpEquipment {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Impeller : PumpEquipment {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SubTaggedColumnSection : Equipment {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ColumnInternalsArrangement : Equipment {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TaggedColumnSection : Equipment {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InstrumentComponent : Component {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Text : Component {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Justification;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Width;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Height;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DependantAttribute;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ItemID;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string String;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Font;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TextAngle;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InstrumentationLoopFunction : Component {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PropertyBreak : Component {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsulationSymbol : Component {

        /// <remarks/>
        public PipingNetworkSegment Owner;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PipingNetworkSegment : PlantItem {

        /// <remarks/>
        public Connection Connection;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CenterLine", typeof(CenterLine))]
        [System.Xml.Serialization.XmlElementAttribute("Component", typeof(Component))]
        [System.Xml.Serialization.XmlElementAttribute("InsulationSymbol", typeof(InsulationSymbol))]
        [System.Xml.Serialization.XmlElementAttribute("PipeFlowArrow", typeof(PipeFlowArrow))]
        [System.Xml.Serialization.XmlElementAttribute("PipeOffPageConnector", typeof(PipeOffPageConnector))]
        [System.Xml.Serialization.XmlElementAttribute("PipingComponent", typeof(PipingComponent))]
        [System.Xml.Serialization.XmlElementAttribute("ProcessInstrument", typeof(ProcessInstrument))]
        [System.Xml.Serialization.XmlElementAttribute("PropertyBreak", typeof(PropertyBreak))]
        public Component[] Items;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NominalDiameter")]
        public NominalDiameter[] NominalDiameter;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InstrumentConnection")]
        public InstrumentConnection[] InstrumentConnection;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Connection : A_LoopObj {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FromID;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ToID;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int FromNode;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FromNodeSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ToNode;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ToNodeSpecified;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CenterLine : Component {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Coordinate")]
        public Coordinate[] Coordinate;

        /// <remarks/>
        public PipingNetworkSegment Owner;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int NumPoints;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PipeFlowArrow : Component {

        /// <remarks/>
        public PipingNetworkSegment Owner;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PipeOffPageConnector : Component {

        /// <remarks/>
        public PipeOffPageConnectorReference PipeOffPageConnectorReference;

        /// <remarks/>
        public CrossPageConnection CrossPageConnection;

        /// <remarks/>
        public PipingNetworkSegment Owner;
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PipeOffPageConnectorReferenceByNumber))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PipeOffPageConnectorReference : PlantItem {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PipeOffPageConnectorReferenceByNumber : PipeOffPageConnectorReference {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CrossPageConnection : A_LoopObj {

        /// <remarks/>
        public LinkedPersistentID LinkedPersistentID;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DrawingName;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LinkLabel;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LinkedPersistentID : Component {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Identifier;
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PipeTee))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Gap))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PipingComponent : Component {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NominalDiameter")]
        public NominalDiameter[] NominalDiameter;

        /// <remarks/>
        public PipingNetworkSegment Owner;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NominalDiameter : A_LoopObj {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double Value;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PipeTee : PipingComponent {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Gap : PipingComponent {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProcessInstrument : Component {

        /// <remarks/>
        public PipingNetworkSegment Owner;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InstrumentConnection : PlantItem {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProcessInstrumentationFunction : Component {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ProcessSignalGeneratingFunction")]
        public ProcessSignalGeneratingFunction[] ProcessSignalGeneratingFunction;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ActuatingFunction")]
        public ActuatingFunction[] ActuatingFunction;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InformationFlow")]
        public InformationFlow[] InformationFlow;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProcessSignalGeneratingFunction : Component {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ActuatingFunction : Component {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InformationFlow : PlantItem {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CenterLine")]
        public CenterLine[] CenterLine;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PipingComponent")]
        public PipingComponent[] PipingComponent;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PipeOffPageConnector")]
        public PipeOffPageConnector[] PipeOffPageConnector;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ProcessInstrument")]
        public ProcessInstrument[] ProcessInstrument;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PipeFlowArrow")]
        public PipeFlowArrow[] PipeFlowArrow;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Component")]
        public Component[] Component;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Line")]
        public Line[] Line;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PolyLine")]
        public PolyLine[] PolyLine;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Circle")]
        public Circle[] Circle;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Ellipse")]
        public Ellipse[] Ellipse;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TrimmedCurve")]
        public TrimmedCurve[] TrimmedCurve;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Shape")]
        public Shape[] Shape;

        /// <remarks/>
        public Connection Connection;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProcessSignalGeneratingSystem : Component {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ProcessSignalGeneratingSystemComponent")]
        public ProcessSignalGeneratingSystemComponent[] ProcessSignalGeneratingSystemComponent;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProcessSignalGeneratingSystemComponent : Component {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ActuatingSystem : Component {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ActuatingSystemComponent")]
        public ActuatingSystemComponent[] ActuatingSystemComponent;
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OperatedValveReference))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ControlledActuator))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ActuatingSystemComponent : Component {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OperatedValveReference : ActuatingSystemComponent {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ControlledActuator : ActuatingSystemComponent {
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PlantItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PipingNetworkSystem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InstrumentLoop))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InstrumentConnection))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PipeOffPageConnectorReference))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PipeOffPageConnectorReferenceByNumber))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PipingNetworkSegment))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InformationFlow))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Component))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Text))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InstrumentationLoopFunction))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PropertyBreak))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InsulationSymbol))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PipeFlowArrow))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProcessInstrument))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LinkedPersistentID))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PipeOffPageConnector))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PipingComponent))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PipeTee))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Gap))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CenterLine))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProcessInstrumentationFunction))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProcessSignalGeneratingFunction))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ActuatingFunction))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProcessSignalGeneratingSystem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProcessSignalGeneratingSystemComponent))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ActuatingSystem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ActuatingSystemComponent))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OperatedValveReference))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ControlledActuator))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Label))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InstrumentComponent))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Nozzle))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Equipment))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Chamber))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PumpEquipmentChamber))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PumpEquipment))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Displacer))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Impeller))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SubTaggedColumnSection))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ColumnInternalsArrangement))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TaggedColumnSection))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PipingNode))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PlantModel))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public abstract partial class PlantItemCollection : A_LoopObj {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PipingNetworkSystem : PlantItem {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PipingNetworkSegment")]
        public PipingNetworkSegment[] PipingNetworkSegment;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InstrumentLoop : PlantItem {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SignalLine")]
        public InformationFlow[] SignalLine;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ComponentShapeOfNozzle : ComponentShape {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ComponentShapeOfPipingComponent : ComponentShape {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ComponentShapeOfPipeFlowArrow : ComponentShape {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ComponentShapeOfPipeOffPageConnector : ComponentShape {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ComponentShapeOfInstrumentComponent : ComponentShape {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ComponentShapeOfProcessInstrument : ComponentShape {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ComponentShapeOfProcessInstrumentationFunction : ComponentShape {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ComponentShapeOfInstrumentationLoopFunction : ComponentShape {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ComponentShapeOfProcessSignalGeneratingFunction : ComponentShape {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ComponentShapeOfComponent : ComponentShape {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ComponentShapeOfPropertyBreak : ComponentShape {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ComponentShapeOfControlledActuator : ComponentShape {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ComponentShapeOfInsulationSymbol : ComponentShape {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ComponentShapeOfEquipment : ComponentShape {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PlantStructureItem {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Association")]
        public Association[] Association;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GenericAttributes")]
        public GenericAttributes[] GenericAttributes;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ID;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ComponentClass;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ComponentClassURI;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ShapeCatalogue : A_LoopObj {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Equipment")]
        public ComponentShapeOfEquipment[] Equipment;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Nozzle")]
        public ComponentShapeOfNozzle[] Nozzle;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PipingComponent")]
        public ComponentShapeOfPipingComponent[] PipingComponent;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PipeFlowArrow")]
        public ComponentShapeOfPipeFlowArrow[] PipeFlowArrow;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PipeOffPageConnector")]
        public ComponentShapeOfPipeOffPageConnector[] PipeOffPageConnector;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InstrumentComponent")]
        public ComponentShapeOfInstrumentComponent[] InstrumentComponent;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ProcessInstrument")]
        public ComponentShapeOfProcessInstrument[] ProcessInstrument;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ProcessInstrumentationFunction")]
        public ComponentShapeOfProcessInstrumentationFunction[] ProcessInstrumentationFunction;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InstrumentationLoopFunction")]
        public ComponentShapeOfInstrumentationLoopFunction[] InstrumentationLoopFunction;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ProcessSignalGeneratingFunction")]
        public ComponentShapeOfProcessSignalGeneratingFunction[] ProcessSignalGeneratingFunction;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Component")]
        public ComponentShapeOfComponent[] Component;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PropertyBreak")]
        public ComponentShapeOfPropertyBreak[] PropertyBreak;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ActuatingSystemComponent")]
        public ComponentShapeOfControlledActuator[] ActuatingSystemComponent;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InsulationSymbol")]
        public ComponentShapeOfInsulationSymbol[] InsulationSymbol;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DrawingBorder : A_LoopObj {

        /// <remarks/>
        public Presentation Presentation;

        /// <remarks/>
        public Extent Extent;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Line")]
        public Line[] Line;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PolyLine")]
        public PolyLine[] PolyLine;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Circle")]
        public Circle[] Circle;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Ellipse")]
        public Ellipse[] Ellipse;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TrimmedCurve")]
        public TrimmedCurve[] TrimmedCurve;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Shape")]
        public Shape[] Shape;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Label")]
        public Label[] Label;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Text")]
        public Text[] Text;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GenericAttributes")]
        public GenericAttributes[] GenericAttributes;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Size;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SizeURI;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Drawing : A_LoopObj {

        /// <remarks/>
        public Presentation Presentation;

        /// <remarks/>
        public Extent Extent;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Line")]
        public Line[] Line;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PolyLine")]
        public PolyLine[] PolyLine;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Circle")]
        public Circle[] Circle;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Ellipse")]
        public Ellipse[] Ellipse;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Shape")]
        public Shape[] Shape;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Text")]
        public Text[] Text;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Label")]
        public Label[] Label;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InsulationSymbol")]
        public InsulationSymbol[] InsulationSymbol;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Component")]
        public Component[] Component;

        /// <remarks/>
        public DrawingBorder DrawingBorder;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Title;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Type;
    }
}